{% set name = "qupy" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ken-nakanishi/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 34d58f3967b0f4847e07fdc771574696a1295ac9fb4296c2c960efbffcdf1081

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy

test:
  imports:
    - qupy

about:
  home: https://github.com/ken-nakanishi/qupy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'QuPy: A quantum circuit simulator for both CPU and GPU'
  doc_url: https://qupy.readthedocs.io/
  dev_url: https://github.com/ken-nakanishi/qupy

extra:
  recipe-maintainers:
    - ken-nakanishi
