travis:
  secure:
    BINSTAR_TOKEN: ijHAF9JASE4cALmZjGE8YJfPMj/gWFEalTP4ellWlqMr5odI50HvnqtTIn91mLddB7PXq7YpGFUfMEEuTIj4ndvVwSA3U5wgyO3rOY/3qLuY88m3fKfKW+Ou2rThmBz/WiGNhYZz3yvb98WqXC0RKhYzmbjLua0O9/QzY7Y7X0gCy6ojd2cIxcbacSySijFQ/UNZlcjixZlgSrHjOPdTTfPU8Txc5U9JjOFIViq0CVoppE1KtIJYZlm/9EYFHf7vW7Zs1+ZSu4UwEUe3xP3ZE8G8bZwFmy6VAkIs0j7mlcV0fQ2f9V4ZHAaQ5P5l4kkMq6wGCav+oPtzgveEHEma9PTozsFjvtQbVLzHTtpYLDONAm9i5VXDsMHT5oYDJvaa9cXovuKYZTvvMNBaHLEmJ+qHYOUC/dr4pFenxt5imt8lfXE4ReK4x+xIYM7dESltAIUMku5eOiJ+fCN0YgXJt4xQwE0g9mf3evXIBpHC0suDf9I0t7JtEE4KqAuLEQbT58MqFu+UfUSGWfc2dAPN1r7EsmRsCSODyVo7hIXKV9MISQmVwm7dZgE3y8lq1shdbkPg/2kb31W7mZqrzXLVuVskfMfnqii5K3jBD7cj9RyPofBFNxdgY9tN0kyytbg6Jy5vFtuuVHUN72h15W4VdorMQIm8m5QUBVQBn4nMs1Y=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
